- test-plone-4.1.x.cfg
- test-plone-4.2.x.cfg
- test-plone-4.3.x.cfg
- versions.cfg
zope.testrunner 4.4.5 reorders the testing layers.
It seems that we have testing layer isolation problems with the new order.
For new, we pin down the testrunner.
> Pin down zope.testrunner.

- docs/HISTORY.txt
- ftw/upgrade/executioner.py
- ftw/upgrade/tests/test_post_upgrade.py
The order was reversed, it should execute dependencies first.
Fixes #59
> Reverse post upgrade adapter ordering.

- docs/HISTORY.txt
- ftw/upgrade/directory/scaffold.py
- ftw/upgrade/tests/test_command_create.py
There should be an ``__init__.py`` file in the upgrade step directory in order for plone.reload to work properly.
> Update upgrade step scaffold to support plone.reload.

- README.rst
- docs/HISTORY.txt
- ftw/upgrade/command/__init__.py
- ftw/upgrade/command/jsonapi.py
- ftw/upgrade/command/user.py
- ftw/upgrade/command/utils.py
- ftw/upgrade/jsonapi/configure.zcml
- ftw/upgrade/jsonapi/utils.py
- ftw/upgrade/jsonapi/zopeapp.py
- ftw/upgrade/tests/base.py
- ftw/upgrade/tests/test_command_jsonapi.py
- ftw/upgrade/tests/test_command_sites.py
- ftw/upgrade/tests/test_command_user.py
- ftw/upgrade/tests/test_jsonapi_zopeapp.py
`bin/upgrade` authentication currently requires to write the administrator password to the command line (-> bash history) or to shell config file (environment variable), which is not very nice (#68).
This implements a tempfile based authentication, used when neither `--auth` param nor `UPGRADE_AUTHENTICATION` environment variable is used.
**Authentication procedure:**
- The client writes a random 64-byte hash to a tempfile and sends the filename and hash as request header to the server.
- The server reads the tempfile by joining the path with `tempfile.gettempdir()` and compares the value.
- The server creates a Zope-level `system-upgrade` user (when it does not exist).
- The server logs in with the `system-upgrade`.
**Requirements and details:**
- Client and server must be on the same …
> Tempfile based authentication negotiation

- docs/HISTORY.txt
- ftw/upgrade/directory/scanner.py
- ftw/upgrade/tests/builders.py
Fixes the module names so that plone.reload has a chance to reload the upgrade step code.
The problem was an additional `.upgrades` in the module dottenames and that the upgrade step directory package was not loaded properly.
> plone.reload support for upgrade step directory.

- README.rst
- docs/HISTORY.txt
- ftw/upgrade/command/__init__.py
- ftw/upgrade/command/recook.py
- ftw/upgrade/executioner.py
- ftw/upgrade/jsonapi/configure.zcml
- ftw/upgrade/jsonapi/plonesite.py
- ftw/upgrade/resource_registries.py
- ftw/upgrade/tests/base.py
- ftw/upgrade/tests/test_command_recook.py
- ftw/upgrade/tests/test_executioner.py
- ftw/upgrade/tests/test_jsonapi_plonesite.py
- ftw/upgrade/tests/test_resource_registries.py
- Resources are automatically recooked after installing upgrades
- Resources can manually be recooked with `bin/upgrade recook`
Closes #70 (1. and 3.)
/cc @lukasgraf @deiferni
> Recook resources

- docs/HISTORY.txt
- ftw/upgrade/command/jsonapi.py
- ftw/upgrade/command/terminal.py
- ftw/upgrade/command/utils.py
- ftw/upgrade/jsonapi/utils.py
- ftw/upgrade/tests/test_command_fake_terminal.py
- ftw/upgrade/utils.py
When Python is built without curses support, an `ImportError` `_curses` is raised, because blessed tries to import `curses`. This error currently also happens when starting the Zope instance.
1. Starting the Zope instance should not import the command stuff. I've therefore moved the shared function `get_tempfile_authentication_directory` to the `utils` module on root level. This will make the instance bootable but the `ImportError` still occurs when running `bin/upgrade`.
2. The `blessed` package just imports `curses` without any fallback. We can therefore not import anything when we don't have `curses` support. Because of that I've implemented a very simple `FakeTerminal` which fakes the terminal calls we use and just does not format anything. There is a test for the `FakeTerminal`, but …
> Support Python built without curses support

- docs/HISTORY.txt
- ftw/upgrade/command/jsonapi.py
- ftw/upgrade/tests/test_command_jsonapi.py
When an instance is bound to a public interface, the config is ```address 0.0.0.0:8080``` instead of ```address 8080```.
> Command: fix instance discover when bound to public network interface.

- docs/HISTORY.txt
- ftw/upgrade/executioner.py
- ftw/upgrade/tests/test_post_upgrade.py
The post upgrade ordering was changed in #64 to be reversed.
The change in #64 was done out of confusion and did the wrong thing.
This changes it back to the right order:
Given the profiles:
- A -> B
- B -> C
- C -> -
The order should be:
C, B, A
This is important so that policies can change things done by its dependencies.
/cc @mbaechtold @lukasgraf
> Fix post upgrade ordering which was broken since 1.11.0.

- docs/HISTORY.txt
- ftw/upgrade/executioner.py
- ftw/upgrade/tests/test_executioner.py
When installing a product (or profile), quickinstaller stores its version.
When upgrading the package, the version is not updated because it is not reinstalled.
Since upgrading the package should update all things so that it is similar to the new version of the package, we update the package version in quickinstaller to the current product version.
Fixes #79 
/cc @maethu @lukasgraf @simahawk
> Update quickinstaller product version when upgrading a package.

- docs/HISTORY.txt
- ftw/upgrade/browser/manage.py
- ftw/upgrade/jsonapi/utils.py
- ftw/upgrade/workflow.py
Noticed this in the `WorkflowChainUpdater`. You have to return `self` in the `__enter__` method to allow `as` statements like these:
```
with WorkflowChainUpdater(objects) as wcu:
wcu.stuff = other_stuff
```
I also added this to the other context managers where it wasn't already present.
> Return context manager to allow "as" statements.

- docs/HISTORY.txt
- ftw/upgrade/command/jsonapi.py
- ftw/upgrade/jsonapi/utils.py
In certain situations depending on Python version and current
authentication hash the base64 of the authentication header may contain
newlines, which is not valid in HTTP request headers.
Since we do not have special characters in the header value we do not
need to encode it with base64.
Example failure:
```python
Error in test test_tempfile_authentication (ftw.upgrade.tests.test_command_jsonapi.TestAPIRequestor)
Traceback (most recent call last):
File "/Users/jone/projects/python/cache/eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 340, in run
testMethod()
File "/Users/jone/projects/packages/ftw.upgrade/ftw/upgrade/tests/test_command_jsonapi.py", line 58, in test_tempfile_authentication
jsondata = requestor.GET('current_user').json()
File …
```
> Fix authentication problem with bin/upgrade command.

- docs/HISTORY.txt
- ftw/upgrade/executioner.py
- ftw/upgrade/tests/test_executioner.py
This PR adds an `afterCommitHook` that simply logs an info message as soon as the transaction has been committed (or aborted).
This is helpful for very long upgrades where the transaction can get quite large, and takes a while to commit. It then is hard to tell when exactly the transaction is done committing.
[Hooks are not persisted across transaction boundaries](https://github.com/zopefoundation/transaction/blob/a97ce37f47f7e5813d450e931e93c8b8b4544ecd/transaction/interfaces.py#L268-L275) - so no special care has to be taken to make sure the hook is removed:
> Calling a hook "consumes" its registration:  hook registrations do not persist across transactions.
@jone @phgross @deiferni
> Add an afterCommitHook that notifies about the transaction having been committed

- docs/HISTORY.txt
- ftw/upgrade/tests/test_workflow.py
- ftw/upgrade/workflow.py
This PR aims to migrate the States with the workflowhistory migration. Since the workflowhistory has the workflow as key we still have the old states if something would be wrong with the new workflow. It also removes the requirement to manually set the current State after the migration since it now is the correct one and therefore we don't get an additional historyentry for that.
In the tests I also touched some cases which i didn't have to, but i felt like testing the workflow migration with two workflows where the states are called the same isn't optimal.
> migrate states with wfhistory migration.

- docs/HISTORY.txt
- ftw/upgrade/configure.zcml
- ftw/upgrade/events.py
- ftw/upgrade/interfaces.py
- ftw/upgrade/intid/configure.zcml
- ftw/upgrade/intid/migrate.py
- ftw/upgrade/step.py
- ftw/upgrade/testing.py
- ftw/upgrade/tests/test_upgrade_step_intids.py
- setup.py
This PR addresses a potential issue with class-migrations and references to objects from the intid utility.
`five.intid` keeps [a reference](https://github.com/plone/five.intid/blob/master/five/intid/keyreference.py#L71) to the object for which an intid is generated. After a class-migration we need to refresh that reference, otherwise the object will have the wrong class wenn loaded from intid `getObejct`/`queryObject` before it is accessed otherwise. In the worst case, i.e. when combined with other changes to the referenced object, this could lead to the object swapping back its class persistently to the old class it had before migration.
> Refresh references from intid utility to objects after a class migration

- README.rst
- docs/HISTORY.txt
- ftw/upgrade/command/terminal.py
- setup.py
- test-plone-4.3.x-with-blessed.cfg
Fixes #87 
No longer have `blessed` as a standard dependency.
`blessed` is used for colorizing the terminal output of `bin/upgrade`.
There is already a fallback for when blessed could not be properly installed (depends on the python installation), so we can just make the dependency optional.
For having colorized terminal output we now need to use the `ftw.upgrade [colors]` extras.
> Remove "blessed" dependency

- docs/HISTORY.txt
- ftw/upgrade/command/__init__.py
- ftw/upgrade/command/jsonapi.py
- ftw/upgrade/tests/test_command_jsonapi.py
Zope instances used to only be detected when the were named "instance*".
This change adds support for any name.
Fixes #91
/cc @fredvd
> Change instance detection to support any name.

- docs/HISTORY.txt
- ftw/upgrade/command/sites.py
This would fail when a site had non-ascii characters in its title.
Sample traceback:
```
$ bin/upgrade sites
/cz                  Zeelandia | Suroviny pro pekaře, cukráře a gastronomii
...
$ bin/upgrade sites | less
Traceback (most recent call last):
File "bin/upgrade", line 314, in <module>
sys.exit(ftw.upgrade.command.main())
File "/Users/maurits/clients/zeelandia/zeelandia.landen/develop/ftw.upgrade/ftw/upgrade/command/__init__.py", line 144, in main
UpgradeCommand()()
File "/Users/maurits/clients/zeelandia/zeelandia.landen/develop/ftw.upgrade/ftw/upgrade/command/__init__.py", line 140, in __call__
args.func(args)
File "/Users/maurits/clients/zeelandia/zeelandia.landen/develop/ftw.upgrade/ftw/upgrade/command/jsonapi.py", line 113, in func_wrapper
return func(args, requestor)
File …
```
> Prevented UnicodeEncodeError when piping output of 'bin/upgrade sites'.

- README.rst
Make docs regarding the installation of the `bin/upgrade` console script more clear.
Closes #90
> Update docs regarding installation of console script.

- docs/HISTORY.txt
- ftw/upgrade/command/__init__.py
- ftw/upgrade/command/jsonapi.py
By default print only our own logging, on info level or higher.  With the new `--verbose` option print all loggers (so also from other packages like `requests`) at debug level and higher.
With this added, the `--all-sites` option from pull request #99 will visibly log which site it is currently handling.
This is probably my last pull request of this day. ;-)
> Configure logging for the command line utility.

- docs/HISTORY.txt
- ftw/upgrade/command/install.py
- ftw/upgrade/executioner.py
- ftw/upgrade/jsonapi/configure.zcml
- ftw/upgrade/jsonapi/exceptions.py
- ftw/upgrade/jsonapi/plonesite.py
- ftw/upgrade/tests/test_jsonapi_plonesite.py
Profiles are only applied once.
Example command line:
`bin/upgrade install --site Plone --profiles Products.PloneFormGen:default`
This implements my request from issue #93.
> Added support for installing profiles.

- docs/HISTORY.txt
- ftw/upgrade/command/__init__.py
- ftw/upgrade/command/jsonapi.py
- ftw/upgrade/command/utils.py
- ftw/upgrade/tests/test_command_list.py
This iterates over all sites and performs the specified command on each of them.
A failing command for one site will stop the entire command.
This was initially rejected in issue #81, but I had a brain wave on how to do it and this seems to work fine. So maybe it is acceptable after all.
I have a Zope instance with 14 Plone Sites, so this would be nice to have. :-)
> Added '--all-sites' option.

- docs/HISTORY.txt
- ftw/upgrade/directory/scaffold.py
- ftw/upgrade/tests/test_command_create.py
- ftw/upgrade/tests/test_directory_scaffold.py
The upgrade step scaffolding had trouble when non-alphanumeric characters such as dots were used.
Closes #102.
/cc @bierik
> Fix bug in scaffolding with dots.

- README.rst
- docs/HISTORY.txt
- ftw/upgrade/command/__init__.py
- ftw/upgrade/command/plone_upgrade_needed.py
- ftw/upgrade/jsonapi/configure.zcml
- ftw/upgrade/jsonapi/plonesite.py
- ftw/upgrade/tests/test_command_plone_upgrade_needed.py
- ftw/upgrade/tests/test_jsonapi_plonesite.py
- adds a jsonapi endpoint "plone_upgrade_needed"
- adds a commaind "plone_upgrade_needed"
- both returning "true" when a Plone upgrade is needed
according to portal_migration.
> Add ``bin/upgrade plone_upgrade_needed`` command.

- README.rst
- docs/HISTORY.txt
- ftw/upgrade/directory/wrapper.py
- ftw/upgrade/step.py
- ftw/upgrade/tests/test_directory_upgrade_steps.py
- ftw/upgrade/tests/test_upgrade_step.py
Provide the attributes ``base_profile`` and ``target_version`` on upgrade steps when using the ``upgrade-step:directory`` directive.
This allows for better extension of the upgrade system.
/cc @4teamwork/gever
> Add base_profile and target_version attributes.

- docs/HISTORY.txt
- ftw/upgrade/directory/zcml.py
- ftw/upgrade/tests/test_directory_meta_directive.py
Fix profile version when using `upgrade-step:directory` and having classic upgrade steps but no new ones.
The problem was that when having classic upgrade steps, the generic setup profile version was set to 10000000000000 instead of to the target version of the last classic upgrade.
The problem only occured when:
- There were classic manual upgrade steps registered in ZCML.
- The `upgrade-step:directory` was used.
- There were not yet an `upgrade-step:directory` based upgrades.
/cc @4teamwork/gever @maethu
> Fix wrong default profile version in certain cases.

- docs/HISTORY.txt
- ftw/upgrade/directory/recorder.py
- ftw/upgrade/jsonapi/utils.py
- ftw/upgrade/testing.py
- ftw/upgrade/tests/base.py
- test-plone-4.3.x.cfg
Closes #105
This makes it possible to run upgrades with the `bin/upgrade` executable when having `plone.protect`'s CSRF auto protection enabled.
- Automatically disable CSRF-protection for all requests since we have our custom authentication mechanism in Place, working with a file on the server disk.
- Change recorder storage to not be initialized on read so that we do not create accidental writes when accessing the `manage-upgrades` view.
@deiferni may you take a look at this one?
> Disable automatics CSRF protection for authorized jsonapi requests

- README.rst
- docs/HISTORY.txt
- ftw/upgrade/command/install.py
- ftw/upgrade/executioner.py
- ftw/upgrade/jsonapi/plonesite.py
- ftw/upgrade/tests/base.py
- ftw/upgrade/tests/test_command_install.py
- ftw/upgrade/tests/test_executioner.py
- ftw/upgrade/tests/test_jsonapi_plonesite.py
- ftw/upgrade/tests/test_upgrade_step.py
Add an option to force reinstalling already installed profiles.
The option is added on all layers (bin/upgrade command, jsonapi, executioner).
/cc @lukasgraf
> Add option to force reinstall already installed profiles.

- docs/HISTORY.txt
- ftw/upgrade/command/install.py
- ftw/upgrade/command/plone_upgrade.py
With the newest "requests" (=2.11.0) streamed responses cannot be automatically decoded.
We now do this manually but always with utf-8, which should be quite a safe bet in our environment.
Closes #113
> Fix NoneType AttributeError with newest requests module.

- docs/HISTORY.txt
- ftw/upgrade/migration.py
It is possible to construct objects so that `extract_relations` (`p.a.relationfield`) extracts UID-strings as relation, instead of relation objects.
When feeding that to `_setRelation` (`z3c.relationfield`) for updating the relation catalog, it does not understand it and fail with an `AttributeError`.
We now skip those invalid relations and log a warning.
> Migration: skip invalid relations.

- docs/HISTORY.txt
- ftw/upgrade/migration.py
The migration use to support IRelationChoice fields explicitly, but when having a relation list field without a value_type, it has the standard value type IRelation, which we also want to support.
> Migration: support all types of standard relation fields.

- docs/HISTORY.txt
- ftw/upgrade/migration.py
When the blob was empty (e.g. no file uploaded) on the old object it was not converted and thus the old value was directly set on the new object, causing errors.
We now either migrate the blob or return None.
> Migration: do not migrate empty blobs.

- README.rst
- docs/HISTORY.txt
- ftw/upgrade/step.py
- ftw/upgrade/tests/test_upgrade_step.py
- setup.py
When adding a new dependency, I want to ensure in an upgrade step that this new dependency is installed.
If, however, the installation already has this dependency installed and probably configured / customized, I do not want to reinstall its Generic Setup profile because this may change configured settings back to defaults.
The new `ensure_profile_installed` does only install a Generic Setup profile when it is not yet installed. For example:
```python
from ftw.upgrade import UpgradeStep
class InstallFtwSimplelayout(UpgradeStep):
"""Install ftw.simplelayout.
"""
def __call__(self):
self.install_upgrade_profile()
self.ensure_profile_installed('profile-ftw.simplelayout:default')
```
---
Since the `ensure_profile_installed` needs to check for profile / product installation, I also have added …
> Upgrade step: profile / product methods

- docs/HISTORY.txt
- ftw/upgrade/directory/subscribers.py
When importing a tarball with Generic Setup the ftw.upgrade subscriber failed because the tarball was not bound to a profile.
> Fix support for GS import by tarball upload.

- docs/HISTORY.txt
- ftw/upgrade/step.py
- ftw/upgrade/tests/test_upgrade_step.py
- ftw/upgrade/utils.py
This PR adds a method that allows to remove a portlet manager, that cannot be imported any more, from the persistent registry.
It also makes sure that utilities are really, really unregistered 😁 .
> Add method to remove a previously uninstalled portlet manager from the persistent registry.

- docs/HISTORY.txt
- ftw/upgrade/executioner.py
- ftw/upgrade/tests/base.py
- ftw/upgrade/tests/test_executioner.py
- ftw/upgrade/tests/test_gatherer.py
When only an orphan upgrade step is installed, it might downgrade the installed version of its profile.
Solution:
Only set the version when it is higher than the current version.
Fixes #126
> do not downgrade installed versions.

- README.rst
- docs/HISTORY.txt
- ftw/upgrade/directory/zcml.py
- ftw/upgrade/tests/builders.py
- ftw/upgrade/tests/test_directory_meta_directive.py
- ftw/upgrade/utils.py
The new "dependencies" option allows to declare Generic Setup profile dependencies which are only relevant when installing upgrade steps.
It influences the topological dependency sorting in the manage-upgrades view.
See the readme changes for more details.
FYI @lukasgraf
> add upgrade-step:directory dependencies option.

- docs/HISTORY.txt
- ftw/upgrade/migration.py
- ftw/upgrade/tests/test_migration.py
The migration of an object removes the old object from the parent and
appends the new one. This previously resulted in a new order which depends on the
order of the migration of the objects.
> InplaceMigrator: Preserve object position in parent.

- docs/HISTORY.txt
- ftw/upgrade/step.py
- ftw/upgrade/tests/test_migration.py
- ftw/upgrade/tests/test_upgrade_step.py
- test-plone-4.3.7.cfg
Avoid coverriding customizations by reinstalling already installed profiles while upgrading (Plone>=4.3.8).
If an Upgrade in `A` installes the new dependency `B`, which depends on `C` but `C` was already installed and customized in `A` earlier, we should not reinstall `C` so that we can avoid lossing `A`'s customizations.
This is simply done by using the dependency strategy `DEPENDENCY_STRATEGY_NEW`, which is available in `Products.GenericSetup >= 1.8` (`Plone >= 4.3.8`).
Closes #125
FYI @buchi @lukasgraf
> Avoid profile reinstall in upgrades.

- docs/HISTORY.txt
- ftw/upgrade/executioner.py
- ftw/upgrade/tests/test_executioner.py
In the version 2.3.0 we have introduced a check that avoids downgrading when installing orphan upgrades.
Since the version comparison is made as string and not with parsing the version, it will cause wrong results when switching versioning systems (e.g. from 4020 to 20160101000000).
The effect will be that upgrades are proposed which should not be.
> fix bug when setting versions after upgrading.

- ftw/upgrade/tests/base.py
- ftw/upgrade/tests/test_jsonapi_plonesite.py
- ftw/upgrade/tests/test_jsonapi_zopeapp.py
The newest ftw.testbrowser has changed regarding HTTP error exceptions.
The new browser.expect_api_error context manager makes it easier to test ftw.upgrade's api errors.
> Restore compatibility with newest ftw.testbrowser.

- docs/HISTORY.txt
- ftw/upgrade/browser/manage.py
- ftw/upgrade/progresslogger.py
- ftw/upgrade/tests/test_manage_view.py
- ftw/upgrade/tests/test_progresslogger.py
Fixes https://github.com/4teamwork/ftw.upgrade/issues/135
If the `ProcessLogger` is used as an iterator and there is an exception, the last item will be logged. If the `ProcessLogger` is used by manually calling it after each step the current iteration number is logged since the current item can not reliably be determined.
There is a display bug in the ajax upgrade output in the browser. Tags are not escaped which causes `repr` logs to disappear.
This is fixed in the second commit.
> Log current item in ProcessLogger if logger exits unexpectedly

- docs/HISTORY.txt
- ftw/upgrade/configure.zcml
- ftw/upgrade/executioner.py
- ftw/upgrade/indexing.py
- ftw/upgrade/interfaces.py
- ftw/upgrade/testing.py
- ftw/upgrade/tests/base.py
- ftw/upgrade/tests/test_executioner.py
- ftw/upgrade/tests/test_upgrade_step.py
- test-plone-4.3.x-with-collective.indexing.cfg
This PR contains an alternative strategy to #14, instead of disabling `collective.indexing` while upgrading we log the reindex progress.
The PR adds an `IIndexQueueProcessor`-utility for `collective.indexing`. The new `LoggingQueueProcessor` utility logs (only during upgrades) whenever `collective.indexing` is processing its queue. This is especially helpful since reindexing may take quite a while. Before the upgrade would just hang without logging, which could be quite irritating for the poor person executing an upgrade on a deployment with a lot of content. With this PR it will output the following:
The utility will be registered all the time, but care is taken to only log while upgrading. I thought that this would be the better approach than attempting to dynamically …
> Log collective.indexing progress while upgrading.

- test-plone-4.3.x.cfg
Test failure in question:
https://ci.4teamwork.ch/builds/90213/tasks/131576#bottom
Since we updated to the **latest Plone 4.3.x KGS** for test buildouts in 4teamwork/ftw-buildouts#83 we get the a more recent version of `plone4.csrffixes` (`1.1` instead of `1.0`).
Since `plone4.csrffixes == 1.1` now contains a [version constraint on `plone.protect >= 3.0.19`](), we need to bump it here.
@jone should we potentially also pin those other version contraints (`plone.keyring` and `plone.locking` here, even though they currently work?)
> Bump plone.protect to 3.0.19 in test-plone-4.3.x.cfg to fix tests

- docs/HISTORY.txt
- ftw/upgrade/tests/test_utils.py
- ftw/upgrade/utils.py
Fix a bug which caused ``bin/upgrade`` to fail when the ``var`` directory had the setguid flag active.
> Support setguid flag in bin/upgrade authentication.

- docs/HISTORY.txt
- ftw/upgrade/tests/test_utils.py
- ftw/upgrade/utils.py
Support using ``bin/upgrade`` by another user than the Zope server
with less strict security checks.
- The owner of the token file is no longer verified.
- The token directory may be writeable by the owner group.
We assume that the `tmp` directory within the buildout can only be
accessed by trusted users.
> Add multi user support for upgrade command.

- docs/HISTORY.txt
- ftw/upgrade/command/jsonapi.py
- ftw/upgrade/jsonapi/utils.py
In order to support having a specific service user, which runs zope but does not do any other things, such as deploying, we need to support different users using `bin/upgrade` and running zope.
In order to do that we must create the authentication files with a mod so that the group can read it, assuming that the maintenance user and the service user have a shared primary group.
> Fix tempfile authentication when created by different user.

- ftw/upgrade/command/install.py
- ftw/upgrade/command/plone_upgrade.py
- ftw/upgrade/tests/test_command_install.py
When bin/upgrade is ran in a terminal with LC_ALL=C, printed unicodes will be converted to the terminal encoding (ASCII). Since umlauts are not part of ASCII it will fail.
By already encoding unicodes to bytestrings we can awoid that print will convert the strings. If the terminal really cannot print those characters it will display placeholders instead.
Fixes #141
> Fix encoding issues in ASCII terminals.

- README.rst
- docs/HISTORY.txt
- ftw/upgrade/step.py
- ftw/upgrade/tests/test_upgrade_step.py
- setup.py
The upgrade step methods ``catalog_unrestricted_get_object``, ``catalog_unrestricted_search`` (with ``full_objects=True``) and ``objects`` will remove broken brains from the catalog.
When a brain's object cannot be loaded because it does no longer exist, those methods will cause the catalog brain to be removed from the catalog.
This will increase the changes that an upgrade will pass even when the catalog is inconsistent. It will also help cleaning up inconsistent state in the catalog on the go.
A brain is considered dead when a ``KeyError`` occurs while trying to find the object by unrestricted-traversing the path of the brain.
> Remove broken brains from catalog.

- README.rst
- docs/HISTORY.txt
- ftw/upgrade/step.py
- ftw/upgrade/workflow.py
Use a `SavepointIterator` in the `WorkflowSecurityUpdater` in order not to exceed memory.
> Fix memory leak.

- README.rst
- docs/HISTORY.txt
- ftw/upgrade/tests/test_savepoint_iterator.py
- ftw/upgrade/utils.py
Let the SavepointIterator ~minimize~ _garbage collect_ the connection cache in order to free up memory.
After a savepoint is used for moving the data from the memory to the disk we need to ~minimize~ _garbage collect_ the connection cache so that the amount of object is reduced to the allowed cache size.
This allows us to keep the memory footprint low.
Here is an example of the impact of this change in a test which uses the `WorkflowSecurityUpdater`, which updates the security of content objects and uses the `SavepointIterator`.
Before (without cache optimization):
After (with cacheGC and zodb-cache-size reconfiguration; see below):
> Reduce memory footprint in SavepointIterator by garbage collecting connection cache.

- docs/HISTORY.txt
- ftw/upgrade/executioner.py
- ftw/upgrade/utils.py
Call the memory optimization function after each executed upgrade step in order to prevent problems when executing multiple memory-intense upgrade steps in a row, where the upgrade step are not using the savepoint iterator.
> Optimize memory footprint after every upgrade step.

- README.rst
- docs/HISTORY.txt
- ftw/upgrade/tests/test_savepoint_iterator.py
- ftw/upgrade/tests/test_upgrade_step.py
- ftw/upgrade/utils.py
- ftw/upgrade/workflow.py
- Enable the savepoint iterator by default. This affects primarely the `self.objects` method.
- Configure the default savepoint threshold to 1000.
- Make the default savepoint threshold configurable with the environment variable `UPGRADE_SAVEPOINT_THRESHOLD`, so that it can be fine tuned for each environment / host.
When passing a threshold to the iterator, use:
- `None` to use default threshold configured in the environment variable
- `False` to disable the iterator explicitly.
> Enable the savepoint iterator by default.

- docs/HISTORY.txt
- ftw/upgrade/command/install.py
- ftw/upgrade/jsonapi/plonesite.py
- ftw/upgrade/tests/test_command_install.py
- ftw/upgrade/tests/test_jsonapi_plonesite.py
Solves #155
While `bin/install --proposed` still installs all upgrades for _all_ profiles, we now can also install the proposed upgrades of _specific_ profiles with `bin/install --proposed pkg.one:default pkg.two:default`.
I also changed the argument-metavars in the helptext of `bin/upgrade install` to be more precise:
```
usage: ./bin/upgrade install [-h] [--auth AUTH] [--verbose]
(--site SITE | --pick-site | --last-site | --all-sites)
[--force]
(--upgrades UPGRADE-STEP [UPGRADE-STEP ...] | --proposed [PROFILE [PROFILE ...]] | --profiles PROFILE [PROFILE ...])
```
> Support installing proposed upgrades of specific Generic Setup profiles

- docs/HISTORY.txt
- ftw/upgrade/directory/wrapper.py
- ftw/upgrade/tests/test_directory_meta_directive.py
The interfaces implemented by the upgrade step class are now provided by the wrapper. This allows for classification and checks using interfaces.
> Provide upgrade step handler interfaces and handler class in wrapper.

- docs/HISTORY.txt
- ftw/upgrade/gatherer.py
- ftw/upgrade/tests/test_gatherer.py
The goal of this change is that we do not want to propose upgrades which we already know were executed but the current profile id is too old.
With this change, upgrade steps are never proposed when the upgrade step recorder tells that the upgrade step was already executed. This is especially handy for customizations of the upgrade step recording behavior.
~~This has had the impact that upgrade steps between the current profile version and an upgrade step in the future which is already executed could not be detected as orphan because the the detection was based on the current profile version.  In order to do the orphan detection based on whether later upgrade steps are already installed, the upgrade step processing had to be reversed to be bottom-up.~~
> Do not propose executed upgrades newer than current db version.

- docs/HISTORY.txt
- ftw/upgrade/step.py
- ftw/upgrade/tests/test_upgrade_step.py
Make sure the `remove_broken_browserlayer()` helper doesn't fail if the browser layer registration to be removed doesn't exist (any more).
> Make sure remove_broken_browserlayer doesn't fail if browser layer doesn't exist

- docs/HISTORY.txt
- ftw/upgrade/command/jsonapi.py
- ftw/upgrade/tests/test_command_jsonapi.py
Fixes #163
The command line tool extracts the zope port from the zope.conf. The extraction was not robust enough and tripped when the optional zope.conf setting "ip-address" was used.
This change fixes the problem and adds tests for various zope.conf combinations.
The solution is to expect a whitespace before the address string, which can either be a newline (no indentation) or a space (with indentation).
/cc @mauritsvanrees
> Fix connection problem when zope.conf contains ip-address.

- test-plone-4.3.7.cfg
Especially the pinning for Products.DateRecurringIndex to 2.1 is needed to get tests passing again for 4.3.7.
This is required because in versions newer than 2.1 `Products.DateRecurringIndex` now depends on the `ZODB` egg (instead of `ZODB3`) which results in a version conflict around the `transaction` module on Plone versions which don't use `ZODB` > 3.x yet.
This change was introduced in a [PEP8 commit](https://github.com/collective/Products.DateRecurringIndex/commit/e08fc4bec0281ed700f754087f3a286fc6d1891c) - don't know what to tell ya 😕  
Fixes [current test failures](https://ci.4teamwork.ch/builds/193283/tasks/316398).
> Plone 4.3.7 tests: Pin previously unpinned p.a.contenttypes dependencies

- docs/HISTORY.txt
- ftw/upgrade/browser/manage.py
In order to avoid an encoding in Plone >= 5.1.5 problem when not using the main template, Diazo should be disabled for non-main-template views.
> Disable Diazo on upgrades-plain for Plone 5.1.5 support.

- docs/HISTORY.txt
- ftw/upgrade/tests/base.py
- ftw/upgrade/tests/test_command_jsonapi.py
Currently `CommandAndInstance` tests on Plone 5 are failing **when run locally** with
```
AssertionError: Expected exit code 0, got 1 for "/private/var/folders/..._/sample-buildout/bin/upgrade sites --json".
Output:
ERROR: No running Plone instance detected.
```
The reason for these failures is, that when run locally, with Plone 5, the ZServer won't be running on 55001 any more (which our code expects), but on a **dynamic port randomly assigned by the OS**.
The `CommandAndInstance` tests write a pseudo-zconf with the HTTP port where they should expect a running Plone instance (as set up by the `plone.testing.z2.ZServer` layer).
In more recent versions, if `ZSERVER_PORT` is not set, the ZServer layer lets the OS pick a dynamic port for the ZServer it boots, instead of defaulting to port …
> Tests: Choose actual port used by ZServer layer to run CommandAndInstance tests against

- docs/HISTORY.txt
- ftw/upgrade/browser/manage.py
- ftw/upgrade/jsonapi/plonesite.py
- ftw/upgrade/tests/test_command_plone_upgrade.py
- ftw/upgrade/tests/test_jsonapi_plonesite.py
- ftw/upgrade/utils.py
The `portal_migration` tool is registered as a tool utility by Plone. This implies that it can work when fetched "out of thin air" as a utility.
However, this is not strictly the case: Some Plone upgrades make use of `self.REQUEST` (directly or indirectly), which only works if the `portal_migration` tool is wrapped in a `RequestContainer`.
If `portal_migration` is fetched via `getToolByName`, it *won't* be wrapped in a `RequestContainer`, because [`getToolByName` first looks for a utility](https://github.com/zopefoundation/Products.CMFCore/blob/2.3.0/Products/CMFCore/utils.py#L89), and if it finds one, happily returns that.
Instead, the `portal_migration` tool needs to be looked up via acquisition (using `getattr`). This is what Plone itself [does in its `@@plone-upgrade` …
> Make sure to always use a portal_migration tool wrapped in a RequestContainer

- README.rst
Support for Plone 5.1.x has been added in 2.5.0:
https://github.com/4teamwork/ftw.upgrade/blob/466e7930ba67e639af6362218ea0dfb8ca7b049a/docs/HISTORY.txt#L108-L111
Closes https://github.com/4teamwork/ftw.upgrade/issues/176
> Update section "compatibility" in the readme.

- README.rst
- docs/HISTORY.txt
- ftw/upgrade/command/__init__.py
- ftw/upgrade/command/combine_bundles.py
- ftw/upgrade/jsonapi/configure.zcml
- ftw/upgrade/jsonapi/plonesite.py
- ftw/upgrade/tests/base.py
- ftw/upgrade/tests/test_command_combine_bundles.py
This combines JS/CSS bundles together.
Thanks to @lukasgraf for the hints on how to create a new command (via @fredvd).
Strictly speaking, it would be better to not show this command in the help when the site is Plone 4, but I am not sure if that is easily possible. An extra command here should not be a big deal though.
> Added combine_bundles command for Plone 5

- ftw/upgrade/tests/test_upgrade_step.py
The tests were relying on a value in the attribute "rights", which was not actually on the folder object but seems to have been inherited through acquisition. The Plone 4.3.19 release does no longer index parent attributes through acquisition, thus the test was failing.
We have now a more relyable approach by removing an existing index and re-adding it.
> Fix tests after Plone 4.3.19 release.

- docs/HISTORY.txt
- ftw/upgrade/command/install.py
- ftw/upgrade/jsonapi/plonesite.py
- ftw/upgrade/tests/test_jsonapi_plonesite.py
This allows installing upgrades or profiles on a not up-to-date site.
Fixes issue #182.
I updated the `test_execute_upgrades_not_allowed_when_plone_outdated` method.
It was trying a command that failed with a 400 error because the Plone Site was outdated.
But when the Plone Site was *not* outdated, it would have failed with a different 400 error, because the wanted upgrade step did not exist.
Updated it to use an existing upgrade step.
Duplicated the test to check that it works when adding our new `--allow-outdated` option.
I could also combine it into one test if wanted, but technically it is more correct to have two tests.
> Added --allow-outdated option to install command.

- docs/HISTORY.txt
- ftw/upgrade/migration.py
- ftw/upgrade/tests/base.py
- ftw/upgrade/tests/test_migration.py
The Dexterity base class has support for creators (it implements listCreators() and other methods. The dublin core behavior makes it possible to edit the creators.
The migration did work when the dublin core behavior was enabled. But when it was not enabled, the creators was overwritten by the user executing the migration. This change updates the creators.
> Migrate creators even when dublin core behaviors are not enabled.

- README.rst
- docs/HISTORY.txt
- ftw/upgrade/directory/subscribers.py
- ftw/upgrade/tests/test_directory_upgrade_steps.py
For a migration project we need to be able to import the generic setup profile (in an upgrade step) without marking all other upgrade steps as installed.
In order to do that, two changes are made in this PR:
- Upgrade steps are no longer marked as installed when only importing a partial GS profile.
- There is a context manager for temporary disabling the marking of upgrade steps.
See the readme for usage instructions.
> Allow disabling marking upgrade steps as installed on profile import.

- README.rst
- docs/HISTORY.txt
- ftw/upgrade/step.py
- ftw/upgrade/tests/test_upgrade_step.py
`unrestrictedTraverse` may also raise a `NotFound` exception. In this case we want to clean up by removing the brain.
> Cleanup broken catalog brains on NotFound.

- docs/HISTORY.txt
- ftw/upgrade/migration.py
This was necessary in bl.web AT -> DX migration for 'ftw.file.File's where many Files were found to not be in the IntIds catalog.
An alternative might be to call `plone.app.intid.setuphandlers.register_all_content_for_intids` at the start of that upgrade step
related to https://github.com/4teamwork/bl.web/issues/584
> Fix missing values in IntIds catalog as we go in migrate_intid()

- docs/HISTORY.txt
- setup.py
`ftw.upgrade` makes use of `six` a lot, but it was not declared as a direct dependency in `setup.py` until now.
Closes https://github.com/4teamwork/ftw.upgrade/issues/198
> Add "six" to the list of dependencies.

- docs/HISTORY.txt
- ftw/upgrade/migration.py
When using ftw.upgrade to run a upgrade_step in Plone 5.2 and python3 to migrate some contents to another content-type, I run into this error:
```
2020-07-16 10:54:26,954 ERROR   [ftw.upgrade:39][waitress] FAILED
Traceback (most recent call last):
File "/home/erral/downloads/eggs/ftw.upgrade-3.0.1-py3.7.egg/ftw/upgrade/jsonapi/plonesite.py", line 196, in _install_upgrades
*api_ids, propose_deferrable=propose_deferrable)
File "/home/erral/downloads/eggs/ftw.upgrade-3.0.1-py3.7.egg/ftw/upgrade/executioner.py", line 62, in install_upgrades_by_api_ids
return self.install(data)
File "/home/erral/downloads/eggs/ftw.upgrade-3.0.1-py3.7.egg/ftw/upgrade/executioner.py", line 48, in install
self._upgrade_profile(profileid, upgradeids)
File …
```
> Check for six.binary_type to avoid AttributeErrors when running under python3

- docs/HISTORY.txt
- setup.py
Do not depend anymore on argparse because it is already included in
Python 2.7 and in Python 3 since version 3.2
Fixes #209
> Do not depend anymore on argparse

- docs/HISTORY.txt
- ftw/upgrade/directory/scanner.py
- ftw/upgrade/tests/test_directory_scanner.py
Remove the warnings:
```
.../ftw.upgrade/ftw/upgrade/directory/scanner.py:10: DeprecationWarning: the imp module is deprecated in favour of importlib; 
.../ftw.upgrade/ftw/upgrade/directory/scanner.py:40: ResourceWarning: unclosed file ...
```
when using ftw.upgrade on Python3.
Fixes #211
> Use importlib when on Python3

- docs/HISTORY.txt
- ftw/upgrade/resource_registries.py
I see this when migrating from Plone 4.3 to 5.2 when I want to run a small upgrade step before doing the plone-upgrade:
```
$ bin/upgrade install --site minaraad --allow-outdated --upgrades 5200@Products.minaraad:default
2021-01-05 10:22:17,980 INFO    [ftw.upgrade:147][waitress-0] ______________________________________________________________________
2021-01-05 10:22:17,981 INFO    [ftw.upgrade:149][waitress-0] UPGRADE STEP Products.minaraad:default: Pre 5.2 cleanup
2021-01-05 10:22:17,982 INFO    [ftw.upgrade:156][waitress-0] Ran upgrade step Pre 5.2 cleanup for profile Products.minaraad:default
2021-01-05 10:22:17,982 INFO    [ftw.upgrade:159][waitress-0] Upgrade step duration: 1 second
2021-01-05 10:22:17,987 ERROR   [ftw.upgrade:39][waitress-0] FAILED
Traceback (most recent call …
```
> Do not call cookResources on dummy old resource registry tools.

- README.rst
- docs/HISTORY.txt
- ftw/upgrade/command/install.py
- ftw/upgrade/executioner.py
- ftw/upgrade/jsonapi/plonesite.py
- ftw/upgrade/tests/base.py
- ftw/upgrade/tests/test_command_install.py
- ftw/upgrade/tests/test_executioner.py
- test-plone-5.2.x-py37.cfg
When installing a lot of potentially long running upgrades at once we would sometimes like to be able to make sure that each individual upgrade is committed after it has been installed successfully.
For this purpose we add an `--intermediate-commit` flag. If it is toggled on a `commit` will be fired after each upgrade is installed.
Considerations:
- The flag is only available via command line and api. It has not been exposed in the upgrade view.
- The transaction notes will be split into several parts when installing upgrades. There is also a very short final transaction which mostly calls the after upgrade hooks. ![Screenshot 2021-06-21 at 12 14 20](https://user-images.githubusercontent.com/736583/122750611-07ec1200-d28f-11eb-90f4-1c62068b0d12.png)
- Writing the last installed version …
> Add intermediate commit option to commit the transaction after each installed upgrade.

- ftw/upgrade/tests/test_upgrade_step.py
The order of catalog results is not guaranteed and without any sorting parameters order can be arbitrary. This test seems to be flaky occasionally and order is not relevant in this case. We are just interested in the result set but not the order in this case.
> Fix test comparing list against arbitrary order.

- ftw/upgrade/tests/base.py
- ftw/upgrade/tests/helpers.py
- ftw/upgrade/tests/test_command_install.py
- ftw/upgrade/tests/test_executioner.py
Asserting against runtime with no means of either overriding how we log during tests or how time is measured will lead to test failures when CPU time available is scarce.
As this has now happened several times we truncate concrete runtime from the logs only comparing against a placeholder.
> Truncate duration from log entries in tests.

- docs/HISTORY.txt
- ftw/upgrade/step.py
- ftw/upgrade/tests/test_upgrade_step.py
- ftw/upgrade/tests/test_upgrade_step_intids.py
I'm not sure why we don't have a method to iterate over the brains. We don't always want to get the objects.
For https://4teamwork.atlassian.net/browse/CA-2785
> Add method to iterate over brains in upgrade step.

- docs/HISTORY.txt
- ftw/upgrade/executioner.py
- ftw/upgrade/tests/base.py
- ftw/upgrade/tests/helpers.py
- ftw/upgrade/tests/test_command_install.py
- ftw/upgrade/tests/test_executioner.py
- ftw/upgrade/tests/test_utils.py
- ftw/upgrade/utils.py
- setup.py
Changes here include:
- log memory during upgrades
- write upgrade step duration to statistics file
- check available resources during upgrades and sweep cache if memory is critical
For [CA-3284](https://4teamwork.atlassian.net/browse/CA-3284) and [CA-3289](https://4teamwork.atlassian.net/browse/CA-3289)
> Improve memory management during upgrades

- docs/HISTORY.txt
- ftw/upgrade/command/combine_bundles.py
- ftw/upgrade/command/install.py
- ftw/upgrade/command/jsonapi.py
- ftw/upgrade/command/list_cmd.py
- ftw/upgrade/command/plone_upgrade.py
- ftw/upgrade/command/plone_upgrade_needed.py
- ftw/upgrade/command/recook.py
- ftw/upgrade/command/sites.py
- ftw/upgrade/command/user.py
- ftw/upgrade/tests/test_command_install.py
- ftw/upgrade/tests/test_command_jsonapi.py
- ftw/upgrade/tests/test_command_list.py
Upgrade commands were implemented in such a way that the requests would be made to the first running instance (sorted by name). Normally this should be `instance0`, but because upgrade commands usually get run after restarting the instances, if `instance0` is not reachable yet (for example it is still starting), then another instance would be used. This can be problematic as the other instances might not have been restarted yet (see for example [the update_plone script](https://github.com/4teamwork/opengever-deployments/blob/master/deploy/update_plone#L93)). To remedy this issue we now allow forcing the commands to run on a given instance. Moreover to better handle the case where instances might be restarting, we now retry accessing them until a timeout (of 1 minute) is reached.
For …
> Allow choosing a specific instance to run upgrade commands.

- test-plone-4.3.7.cfg
Nightlies have been failing for some time. `certify` has dropped support for pyhton 2 in version [2020.04.05.2](https://github.com/certifi/python-certifi/releases/tag/2020.04.05.2), but definitely broken the package for python 3 when introducing type annotations (https://github.com/certifi/python-certifi/commit/5f09ea84b97202a41430fed5bb3cbd489d04c18e).
> Pin certifi for plone 4.3.7

- docs/HISTORY.txt
- ftw/upgrade/step.py
- ftw/upgrade/tests/test_upgrade_step.py
- ftw/upgrade/tests/test_workflow.py
- ftw/upgrade/utils.py
- ftw/upgrade/workflow.py
- test-plone-4.3.7.cfg
I also fix the failing nightly build for plone 4.3.7.
Note that I collect information about broken brains but don't do anything with it yet. It could be used in specific upgrade steps though to log all brains that have failed once the upgrade is through.
For https://4teamwork.atlassian.net/browse/CA-4112
> Support dead brains in WorkflowSecurityUpdater.
